# Generated by Django 3.2.4 on 2021-06-29 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210629_0821'),
    ]

    operations = [
        migrations.AddField(
            model_name='images',
            name='register_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
