# Generated by Django 3.2.4 on 2021-06-29 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_images_register_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='images',
            name='register_date',
        ),
    ]
